# Generated by Django 6.0.4 on 2026-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('unit', 'per Unit'), ('meter', 'per Meter'), ('kg', 'per KG'), ('piece', 'per Piece'), ('sqft', 'per Sq.Ft'), ('roll', 'per Roll')], default='unit', max_length=20),
        ),
    ]
