# Generated by Django 6.0.4 on 2026-04-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
    ]
