# Generated by Django 6.0.4 on 2026-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('unit', 'Unit'), ('meter', 'Meter'), ('kg', 'KG'), ('piece', 'Piece'), ('sqft', 'Sq.Ft'), ('roll', 'Roll')], default='unit', max_length=20),
        ),
    ]
