# Generated by Django 6.0.4 on 2026-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
