# Generated by Django 5.2.14 on 2026-05-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma separated e.g. Brown,Black,White', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma separated e.g. 6x7ft,7x8ft,8x9ft', max_length=300, null=True),
        ),
    ]
