# Generated by Django 5.2.14 on 2026-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_colors_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated e.g. 7ft,8ft,9ft,10ft — add * to mark out of stock e.g. 9ft*', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Comma-separated e.g. 60x30x45cm, 90x40x75cm, 120x50x90cm', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma-separated e.g. Brown,Black,White', max_length=300, null=True),
        ),
    ]
