# Generated by Django 5.2.14 on 2026-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_sizes_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Format: size:price — e.g. 7ft:5000,8ft:6500,9ft:8000,10ft:9500 — add * for out of stock: 9ft*:8000', max_length=300, null=True),
        ),
    ]
